# Whether this GitHub repo is engineering related
engineering_project: true
# Name of the repository/project in English
english_name: Creative Commons Global Network website
# All technologies used
technologies: PHP, WordPress
# Whether this repository should be featured on the CC Open Source site
featured: false
